name: NPCDestinations_Animator
main: net.livecar.nuttyworks.destinations_animations.DestAnimations_Plugin
description: Plugin for NPC Destinations that enables an NPC animations
version: 2.5.1
api-version: 1.13
author: Sir_Nutty@Spigot
softdepend: [NPC_Destinations]
website: https://www.spigotmc.org/resources/nunpcdestinations-create-living-npcs-1-8-3-1-10-2.13863/
